version: '3'
services:
  app:
    image: portainer/portainer:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: --no-analytics
    ports:
      - "19000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/server/docker-data/portainer:/data"
