name: maven-mvnd
run-name: maven-mvnd-v${{ inputs.MVND_VERSION }}

on:
  workflow_dispatch:
    inputs:
      MVND_VERSION:
        description: 'mvnd Version'
        required: true
        default: '0.8.2'
        
env:
  REGISTRY: docker.io

jobs:
  build:
    name: openjdk-${{ matrix.JDK_VERSION }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        JDK_VERSION: [8, 11, 17, 19]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
        
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: pangliang
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: ${{ inputs.MVND_VERSION }}-openjdk-${{ matrix.JDK_VERSION }}
        uses: docker/build-push-action@v3
        with:
          context: maven-mvnd/
          push: true
          file: maven-mvnd/Dockerfile
          platforms: linux/amd64 #,linux/arm64
          build-args: |
            OPENJDK_IMAGE=eclipse-temurin:${{ matrix.JDK_VERSION }}-jdk-jammy
            MVND_VERSION=${{ inputs.MVND_VERSION }}
          tags: |
            pangliang/maven-mvnd:${{ inputs.MVND_VERSION }}-openjdk-${{ matrix.JDK_VERSION }}
